apiVersion: v1
baseDomain: ${baseDomain}
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {} #TODO
  replicas: ${workerNodeCount}
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {} #TODO
  replicas: ${masterNodeCount}
metadata:
  creationTimestamp: null
  name: ${clustername}
networking:
  clusterNetwork:
  - cidr: ${cluster-network-cidr}
    hostPrefix: ${host-prefix}
  machineNetwork:
  - cidr: ${virtual-network-cidr}
  networkType: OpenShiftSDN
  serviceNetwork:
  - ${service-network-cidr} #TODO
platform:
  azure:
    baseDomainResourceGroupName: ${baseDomainResourceGroupName}
    region: ${region}
publish: ${private-public}
pullSecret: '${pullSecret}'
sshKey: ${sshKey}