apiVersion: cde.cpd.ibm.com/v1
kind: CdeProxyService
metadata:
  name: cde-cr
spec:
  version: 4.0.0
  size: "small"
  namespace: zen
  storageClass: STORAGECLASS
  cert_manager_enabled: true
  license:
    accept: true
    license: Enterprise