apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr                                         # This is the recommended name, but you can change it
  namespace: ${NAMESPACE}                                 # Replace with the project where you will install Cloud Pak for Data
spec:
  license:
    accept: true
    license: Enterprise                                   # Specify the Cloud Pak for Data license you purchased
  storageClass: "REPLACE_STORAGECLASS"                    # Replace with the name of a RWX storage class
  zenCoreMetadbStorageClass: "REPLACE_STORAGECLASS"       # (Recommended) Replace with the name of a RWO storage class
  version: "4.0.1"