# SOURCE: https://install.portworx.com/?operator=true&mc=false&kbver=&b=true&s=%22type%3Dgp2%2Csize%3D1024%22&kd=type%3Dgp2%2Csize%3D150&c=px-cluster-3b3afd65-2b70-4107-9bbb-fbd299b1af8c&osft=true&stork=true&csi=true&mon=true&st=k8s&promop=true
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-3b3afd65-2b70-4107-9bbb-fbd299b1af8c
  namespace: kube-system
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&kbver=&b=true&s=%22type%3Dgp2%2Csize%3D1024%22&kd=type%3Dgp2%2Csize%3D150&c=px-cluster-3b3afd65-2b70-4107-9bbb-fbd299b1af8c&osft=true&stork=true&csi=true&mon=true&st=k8s&promop=true"
    portworx.io/is-openshift: "true"
spec:
  image: portworx/oci-monitor:2.6.1.6
  imagePullPolicy: Always
  kvdb:
    internal: true
  cloudStorage:
    deviceSpecs:
    - type=gp2,size=1024
    kvdbDeviceSpec: type=gp2,size=150
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "false"
  autopilot:
    enabled: true
    providers:
    - name: default
      type: prometheus
      params:
        url: http://prometheus:9090
  monitoring:
    prometheus:
      enabled: true
      exportMetrics: true
  featureGates:
    CSI: "true"
